version: '3.8'

services:
  ai-hedge-fund:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped 